---
# file: ufw.yml
- name: ufw | install ufw
  become: yes
  apt: pkg=ufw state=installed

- name: ufw | allow openssh
  become: yes
  ufw: rule=allow name=OpenSSH

- name: ufw | enabled ufw on startup with deny policy
  become: yes
  ufw: state=enabled policy=deny
