# file: users.yml


- name: users | set root root_password
  become: yes
  user: >
    name=root
    password="{{ ffm_root_password }}"
  tags: setup


- name: users | add group deploy
  become: yes
  group: name={{ ffm_deploy_group }} state=present
  tags: setup


- name: users | add user deploy
  become: yes
  user: >
    name={{ ffm_deploy_user }}
    group={{ ffm_deploy_group }}
    password="{{ ffm_deploy_password }}"
    shell=/bin/bash
    state=present
  tags: setup


- name: users | copy ssh pub key to deployment user
  become: yes
  authorized_key: >
    user={{ ffm_deploy_user }}
    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state=present
  tags: setup


- name: users | enable sudoers.d
  become: yes
  lineinfile: >
    dest=/etc/sudoers
    regexp='^#includedir /etc/sudoers.d'
    line='#includedir /etc/sudoers.d'
    state=present
  tags : setup


- name: users | add deploy_user to sudoers
  become: yes
  template: src=user.j2 dest=/etc/sudoers.d/{{ ffm_deploy_user }} mode=0440
  tags: setup
