---
# handlers file for role-first_five_minutes/

# until service bug is resolved, we fire command
# https://github.com/ansible/ansible-modules-core/issues/1170

- name: restart sshd
  become: yes
  command: service ssh restart

- name: restart unattended upgrades
  become: yes
  command: service unattended-upgrades restart

- name: update timezone
  become: yes
  command: dpkg-reconfigure --frontend noninteractive tzdata
